M48
; DRILL file {KiCad (7.0.0)} date Thu Oct  5 11:29:17 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-05T11:29:17+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
%
G90
G05
T1
X5.6881Y-3.02
T1
G00X5.4568Y-3.02
M15
G01X5.447Y-3.02
M16
G05
T0
M30
